SOURCE_CODE/Tourism_Web/Web/Controllers/HopDongController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Web.Models;

namespace Web.Controllers
{
    public class HopDongController : Controller
    {
        TourismModelDataContext db = new TourismModelDataContext("Data Source=BUIDUYHE;Initial Catalog=TourismManage;Integrated Security=True");
        // GET: HopDong
        public ActionResult Index()
        {

            return View();
        }

        // GET: HopDong/Details/5
        public ActionResult Details(HopDong hopDong, int? id)
        {
            var load = db.HopDongs.FirstOrDefault(l => l.MaHD == id);

            var tour = db.Tours.FirstOrDefault(g => g.MaTour == (int)Session["MaTour"]);
            var datTour = db.DatTours.FirstOrDefault(g => g.MaDatTour == (int)Session["MaDatTour"]);
            var tenHD = db.Tours.FirstOrDefault(t => t.MaTour == (int)Session["MaTour"]);

            DatTour makh = db.DatTours.FirstOrDefault(q => q.MaKH == (int)Session["MaDatTour"]);

            datTour.MaKH = (int)Session["MaKH"];


            load.TongTien = TongTien(datTour.SLNguoiLon.GetValueOrDefault(), datTour.SLTreEm.GetValueOrDefault(), tour.Gia.GetValueOrDefault());
            db.SubmitChanges();

            ViewBag.giaTour = tour.Gia;
            ViewBag.slNguoiLon = datTour.SLNguoiLon;
            ViewBag.slTreEm = datTour.SLTreEm;
            ViewBag.TongTien = load.TongTien;





            return View(load);
        }

        // GET: HopDong/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: HopDong/Create
        [HttpPost]
        public ActionResult Create(HopDong hopDong ,int id)
        {

           
            return View();

            //catch
            //{
            //    ViewBag.SuccessMessage = "Bạn đã đặt tour thất bại!";
            //    return View();
            //}
        }
        public decimal TongTien(int SLNguoiLon,int SLTreEm,decimal Gia)
        {
            

            return Gia * SLNguoiLon + Gia * (decimal)(50.0 / 100.0) * SLTreEm;
        }

        // GET: HopDong/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: HopDong/Edit/5
        [HttpPost]
        public ActionResult Edit()
        {
            //var tour = db.Tours.FirstOrDefault(g => g.MaTour == (int)Session["MaTour"]);
            //var datTour = db.DatTours.FirstOrDefault(g => g.MaDatTour == (int)Session["MaDatTour"]);

            //var tenHD = db.Tours.FirstOrDefault(t => t.MaTour == (int)Session["MaTour"]);



            //HopDong s = db.HopDongs.FirstOrDefault(w => w.MaHD == (int)Session["MaHopDong"]);
            //if (s != null)
            //{
            //    s.TenHD = tour.TenTour;
            //    s.NgayKyHD = DateTime.Now;
            //    s.MaTT = 2; // thanh toán onl


            //    s.TongTien = TongTien(datTour.SLNguoiLon.GetValueOrDefault(), datTour.SLTreEm.GetValueOrDefault(), tour.Gia.GetValueOrDefault());




            //    db.SubmitChanges();
            //    ViewBag.giaTour = tour.Gia;
            //    ViewBag.slNguoiLon = datTour.SLNguoiLon;
            //    ViewBag.slTreEm = datTour.SLTreEm;
            //    ViewBag.TongTien = s.TongTien;

            //    //return View();
            //}
            return View();
        }

        
    }
}

SOURCE_CODE/Tourism_Web/Web/Views/HopDong/Create.cshtml
@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/Layout.cshtml";
}

<h2>Create</h2>
<a href="@Url.Action("Details", "HopDong", new { id = Session["MaHopDong"] })" class="btn btn-sm btn-primary px-3" style="border-radius: 0 30px 30px 0;">Xem chi tiết</a>

SOURCE_CODE/Tourism_Web/Web/Views/HopDong/Details.cshtml
@model Web.Models.HopDong

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>HopDong</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.TenHD)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TenHD)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NgayKyHD)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NgayKyHD)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MaNV)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MaNV)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MaDatTour)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MaDatTour)
        </dd>

       <dt>
            @Html.DisplayNameFor(model => model.MaTT)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.MaTT)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TongTien)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.TongTien)
        </dd>

    </dl>
</div>
<p>
    @*@Html.ActionLink("Edit", "Edit", new { id = Model.MaHD }) |*@
    @*@Html.ActionLink("Back to List", "Index")*@
</p>

SOURCE_CODE/Tourism_Web/Web/Views/HopDong/Edit.cshtml
@model Web.Models.HopDong

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/Layout.cshtml";
}

<h2>Edit</h2>

<div>
    <h4>HopDong</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.TenHD)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TenHD)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NgayKyHD)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NgayKyHD)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MaNV)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MaNV)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MaDatTour)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MaDatTour)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MaTT)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MaTT)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TongTien)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TongTien)

        </dd>

    </dl>
</div>
<p>
    @*@Html.ActionLink("Edit", "Edit", new { id = Model.MaHD }) |
        @Html.ActionLink("Back to List", "Index")*@
    <a href="@Url.Action("Details", "HopDong", new { id = Session["MaHopDong"] })" class="btn btn-sm btn-primary px-3" style="border-radius: 0 30px 30px 0;">Xem chi tiết</a>


</p>