SOURCE_CODE/Tourism_Web/Web/Models/DiemDen.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;


namespace Web.Models
{
    public class DiemDen
    {
        public int MaTour { get; set; }
        public byte[] Hinh { get; set; }
        public string TenTour { get; set; }
    }
}

SOURCE_CODE/Tourism_Web/Web/Controllers/DatTourController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Web.Models;
using System.Data.Entity;

namespace Web.Controllers
{
    public class DatTourController : Controller
    {
        TourismModelDataContext db = new TourismModelDataContext("Data Source=BUIDUYHE;Initial Catalog=TourismManage;Integrated Security=True");
        // GET: DatTour
        public ActionResult Index()
        {
            List<DatTour> datTours = db.DatTours.ToList();
            return View(datTours);
        }

        // GET: DatTour/Details/5
        public ActionResult Details(int? id)
        {
            var load = db.DatTours.FirstOrDefault(s => s.MaDatTour == id);
            return View(load);
        }

        // GET: DatTour/Create
        public ActionResult Create()
        {
            return View();

        }

        // POST: DatTour/Create
        // khách hàng đã đăng nhập và đặt tour
        [HttpPost]
        public ActionResult Create(DatTour datTour, int? id)
        {

            //try
            //{
            var madattour = TempData["MaDatTour"];
            var load = db.DatTours.FirstOrDefault(db => db.MaDatTour == (int)TempData["MaDatTour"]);

            load.SLNguoiLon = datTour.SLNguoiLon;
            load.SLTreEm = datTour.SLTreEm;
            db.SubmitChanges();

            TempData["MaDatTourHD"] = madattour;
            return RedirectToAction("Create", "HopDong");
        }
        //        catch
        //        {
        //            ViewBag.DatTourThatBai = "Bạn đã đặt tour thất bại!";
        //            return View();
        //}

        // GET: DatTour/Create
        public ActionResult XacNhanDatTour(int? id)
        {
            System.Diagnostics.Debug.WriteLine($"Received id: {id}");
            Session["MaTour"] = id;
            return View();

        }



        // POST: DatTour/Create
        [HttpPost]
        public ActionResult XacNhanDatTour(FormCollection form, int id)
        {

            if (Session["MaTour"] != null)
            {

                DatTour datTour = new DatTour();
                datTour.NgayLap = DateTime.Now;
                datTour.MaTour = (int)Session["MaTour"];
                datTour.TinhTrang = "Đang xử lý";
                Session["MaTour"] = datTour.MaTour;
                ViewBag.MaTour = datTour.MaTour;
                // MaKH hợp lệ, tiếp tục thêm vào DatTour
                db.DatTours.InsertOnSubmit(datTour);
                db.SubmitChanges();
                Session["TourVuaChon"] = datTour;
                Session["MaDatTour"] = datTour.MaDatTour;

                return RedirectToAction("BookTour");



            }
            else
            {
                return RedirectToAction("Index", "Home");
            }




        }

        // GET: DatTour/Edit/5
        public ActionResult Edit(int? id)
        {
            var load = db.DatTours.FirstOrDefault(s => s.MaDatTour == id);
            return View(load);
        }

        // POST: DatTour/Edit/5
        [HttpPost]
        public ActionResult Edit(DatTour datTour)
        {
            try
            {

                DatTour s = db.DatTours.FirstOrDefault(sa => sa.MaDatTour == datTour.MaDatTour);
                if (s == null)
                {
                    ViewBag.SuccessMessage = "Không tìm thấy Phiếu Đặt Tour!";
                    return View();
                }


                s.NgayLap = DateTime.Now;
                s.MaKH = datTour.MaKH;
                s.SLNguoiLon = datTour.SLNguoiLon;
                s.SLTreEm = datTour.SLTreEm;
                s.MaTour = datTour.MaTour;
                s.TinhTrang = datTour.TinhTrang;



                db.SubmitChanges();
                ViewBag.SuccessMessage = "Bạn đã cập nhật phiết đặt tour thành công!";
                return RedirectToAction("Index");

            }
            catch
            {
                ViewBag.SuccessMessage = "Bạn đã Cập Nhật phiết đặt tour thất bại!";
                return View();
            }

        }

        // GET: DatTour/Delete/5
        public ActionResult Delete(int? id)
        {
            var load = db.DatTours.FirstOrDefault(s => s.MaDatTour == id);
            return View(load);
        }

        // POST: DatTour/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here
                DatTour s = db.DatTours.FirstOrDefault(sa => sa.MaDatTour == id);
                if (s == null)
                {
                    ViewBag.SuccessMessage = "Không tìm thấy Phiếu Đặt Tour!";
                    return View();
                }
                db.DatTours.DeleteOnSubmit(s);
                db.SubmitChanges();
                ViewBag.SuccessMessage = "Bạn đã Xóa phiếu tour thành công!";
                return RedirectToAction("Index");



            }
            catch
            {
                ViewBag.SuccessMessage = "Bạn đã xóa phiết đặt tour thất bại!";
                return View();
            }
        }




        /////////////////////////
        ///// Action để hiển thị form đặt tour
        public ActionResult BookTour()
        {

            //var detail = db.Tours.FirstOrDefault(s => s.MaTour == (int)Session["MaTour"]);


            return View();
        }

        // Action để xử lý thông tin đặt tour từ form
        [HttpPost]
        public ActionResult BookTour(DatTour datTour)
        {
            if (Session["MaDatTour"] != null)
            {
                // Tiếp tục sử dụng giá trị từ Session
                int maDatTour = (int)Session["MaDatTour"];
                DatTour load = db.DatTours.FirstOrDefault(d => d.MaDatTour == maDatTour);
                var tour = db.Tours.FirstOrDefault(t => t.MaTour == (int)Session["MaTour"]);
                // Kiểm tra xem load có null hay không để tránh lỗi tiếp theo

                // Tiếp tục xử lý với đối tượng load
                load.SLNguoiLon = datTour.SLNguoiLon;
                load.SLTreEm = datTour.SLTreEm;


                
                HopDong hopDong = new HopDong();
                hopDong.MaDatTour = (int)Session["MaDatTour"];
                hopDong.NgayKyHD = DateTime.Now;
                hopDong.TenHD = tour.TenTour;
                hopDong.MaTT = 2;
                hopDong.TongTien = 0;


                db.HopDongs.InsertOnSubmit(hopDong);

                db.SubmitChanges();
                Session["MaHopDong"] = hopDong.MaHD;

                if (Session["MaKH"] == null)
                {
                    return RedirectToAction("Create", "DaiDienKH");
                }
                else
                {
                    load.MaKH = (int)Session["MaKH"];
                }


                return RedirectToAction("Create", "HopDong");



            }
            return RedirectToAction("Index", "Home");






            //return RedirectToAction("BookingSuccess");
        }
      
        // Action để hiển thị trang thông báo đặt tour thành công
        public ActionResult BookingSuccess()
        {
            return View();
        }




    }
}

SOURCE_CODE/Tourism_Web/Web/Controllers/ToursController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Mvc.Razor;
using Web.Models;
using System.Data.Linq;

namespace Web.Controllers
{
    public class ToursController : Controller
    {



        TourismModelDataContext db = new TourismModelDataContext("Data Source=BUIDUYHE;Initial Catalog=TourismManage;Integrated Security=True");
        // GET: Tours
        public ActionResult Index(string search = "")
        {

            // Lấy danh sách tour từ cơ sở dữ liệu
            //List<Tour> tours = db.Tours.ToList();
            List<Tour> tours = db.Tours.Where(row => row.TenTour.Contains(search)).ToList();
            // Kiểm tra và tính toán số ngày đi cho mỗi tour
            foreach (var tour in tours)
                {
                    int soNgayDi = TinhSoNgayDi(Convert.ToDateTime( tour.NgayVe), Convert.ToDateTime(tour.NgayDi));

                    ViewBag.SoNgayDi = soNgayDi; // Thêm một thuộc tính vào đối tượng Tour để lưu trữ số ngày đi
                }






            ViewBag.Search = search;
                return View(tours);
            
        }

        private int TinhSoNgayDi(DateTime ngayVe, DateTime ngayDi)
        {
            if (ngayVe >= ngayDi)
            {
                TimeSpan chenhLech = ngayVe.Subtract(ngayDi);
                return chenhLech.Days;
            }
            else
            {
                return 0;
            }
        }
        public ActionResult Detail(int? id)
        {

            //if (id == null)
            //{
            //    return RedirectToAction("ErrorID", "Error");
            //}
            System.Diagnostics.Debug.WriteLine($"Received id: {id}");
            Tour tour = db.Tours.Where(row => row.MaTour == id).FirstOrDefault();
            Session["MaTour"] = id;
            return View(tour);

        }

        public ActionResult DiemDen()
        {
           
            var randomTours = GetRandomTours(4);
            // Chuyển dữ liệu từ model cơ sở dữ liệu sang ViewModel

            //ViewBag.TourImages = randomTours[0].Select(tour => (tour.Hinh1 != null) ? Convert.ToBase64String(tour.Hinh1.ToArray()) : null).ToList();


           



            if (randomTours.Count >= 4)
            {
                ViewBag.Tour1 = randomTours[0].MaTour;
                //ViewBag.Tour2 = randomTours[0].Hinh1;
                ViewBag.Tour3 = randomTours[0].TenTour;

                ViewBag.Tour4 = randomTours[1].MaTour;
                //ViewBag.Tour5 = randomTours[1].Hinh1;
                ViewBag.Tour6 = randomTours[1].TenTour;

                ViewBag.Tour7 = randomTours[2].MaTour;
                //ViewBag.Tour8 = randomTours[2].Hinh1;
                ViewBag.Tour9 = randomTours[2].TenTour;

                ViewBag.Tour10 = randomTours[3].MaTour;
                //ViewBag.Tour11 = randomTours[3].Hinh1;
                ViewBag.Tour12 = randomTours[3].TenTour;
            }
            return View();

            //return View();
        }


 
        private List<Tour> GetRandomTours(int numberOfTours)
        {

            var allTours = db.Tours.ToList();

            // Nếu có ít hơn numberOfTours tour trong cơ sở dữ liệu, lấy tất cả
            if (allTours.Count <= numberOfTours)
            {
                return allTours;
            }

            // Nếu có nhiều hơn numberOfTours tour, lấy ngẫu nhiên numberOfTours tour
            var random = new Random();
            var randomIndexes = Enumerable.Range(0, allTours.Count).OrderBy(x => random.Next()).Take(numberOfTours);

            return randomIndexes.Select(index => allTours[index]).ToList();
        }
        public ActionResult Create()
        {
            return View();
        }

        // POST: Login/Create
        [HttpPost]
        public ActionResult Create(Tour tour, HttpPostedFileBase Hinh1File, HttpPostedFileBase Hinh2File, HttpPostedFileBase Hinh3File, HttpPostedFileBase Hinh4File)
        {
            if (ModelState.IsValid)
            {

                Tour s = new Tour();
                s.TenTour = tour.TenTour;
                s.NgayDi = tour.NgayDi;
                s.NgayVe = tour.NgayVe;
                s.MoTa = tour.MoTa;
                s.Gia = tour.Gia;
                s.DiemKhoiHanh = tour.DiemKhoiHanh;
                s.SoGhe = tour.SoGhe;
                s.GioKhoiHanh = tour.GioKhoiHanh;
                s.MaDiaDiem = tour.MaDiaDiem;
                s.SoNguoiDat = tour.SoNguoiDat;
                s.MaLoaiKS = tour.MaLoaiKS;
                s.MaPT = tour.MaPT;
                s.TinhTrang = tour.TinhTrang;
                if (Hinh1File != null && Hinh1File.ContentLength > 0)
                {
                    s.Hinh1 = ReadFileData(Hinh1File);
                }

                if (Hinh2File != null && Hinh2File.ContentLength > 0)
                {
                    s.Hinh2 = ReadFileData(Hinh2File);
                }

                if (Hinh3File != null && Hinh3File.ContentLength > 0)
                {
                    s.Hinh3 = ReadFileData(Hinh3File);
                }

                if (Hinh4File != null && Hinh4File.ContentLength > 0)
                {
                    s.Hinh4 = ReadFileData(Hinh4File);
                }
                db.Tours.InsertOnSubmit(s);
                db.SubmitChanges();


                return RedirectToAction("Index", "Home");
            }

            return View(tour);

        }
        private byte[] ReadFileData(HttpPostedFileBase file)
        {
            using (var binaryReader = new BinaryReader(file.InputStream))
            {
                return binaryReader.ReadBytes(file.ContentLength);
            }
        }



    }
}

SOURCE_CODE/Tourism_Web/Web/Views/Tours/Create.cshtml
@model Web.Models.Tour

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/Layout.cshtml";
}
<div class="container-fluid bg-primary py-5 mb-5 hero-header">
    <div class="container py-5">
        <div class="row justify-content-center py-5">
            <div class="col-lg-10 pt-lg-5 mt-lg-5 text-center">
                <h1 class="display-3 text-white mb-3 animated slideInDown">Enjoy Your Vacation With Us</h1>
                <p class="fs-4 text-white mb-4 animated slideInDown">Tempor erat elitr rebum at clita diam amet diam et eos erat ipsum lorem sit</p>
                <form class="position-relative w-75 mx-auto animated slideInDown" action="/Tours/Index">
                    <input class="form-control border-0 rounded-pill w-100 py-3 ps-4 pe-5" type="search" id="search" name="search" placeholder="Eg: Hạ Long " value="@ViewBag.Search">
                    <button type="submit" class="btn btn-primary rounded-pill py-2 px-4 position-absolute top-0 end-0 me-2" style="margin-top: 7px;">Search</button>
                </form>
            </div>
        </div>
    </div>

    <h2>Create</h2>

    @*@using (Html.BeginForm())*@
    @using (Html.BeginForm("Create", "Tours", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        @Html.AntiForgeryToken()

<div class="form-horizontal">
    <h4>Tour</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.TenTour, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.TenTour, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.TenTour, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.NgayDi, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.NgayDi, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.NgayDi, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.NgayVe, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.NgayVe, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.NgayVe, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.MoTa, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.MoTa, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.MoTa, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Gia, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Gia, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Gia, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.DiemKhoiHanh, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.DiemKhoiHanh, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.DiemKhoiHanh, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.SoGhe, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.SoGhe, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.SoGhe, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.GioKhoiHanh, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.GioKhoiHanh, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.GioKhoiHanh, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.MaDiaDiem, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.MaDiaDiem, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.MaDiaDiem, "", new { @class = "text-danger" })
        </div>
    </div>



    <div class="form-group">
        @Html.LabelFor(model => model.MaLoaiKS, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.MaLoaiKS, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.MaLoaiKS, "", new { @class = "text-danger" })
        </div>
    </div>

 



    <form enctype="multipart/form-data" method="post" action="...">
        <div class="form-group">
            @Html.Label("Hình ảnh 1", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" name="Hinh1File" id="Hinh1File" />
            </div>
        </div>
        <div class="form-group">
            @Html.Label("Hình ảnh 2", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" name="Hinh2File" id="Hinh2File" />
            </div>
        </div>
        <div class="form-group">
            @Html.Label("Hình ảnh 3 ", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" name="Hinh3File" id="Hinh3File" />
            </div>
        </div>
        <div class="form-group">
            @Html.Label("Hình ảnh 4", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" name="Hinh4File" id="Hinh4File" />
            </div>
        </div>
    </form>



    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-default" />
        </div>
    </div>
</div>
    }

    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>

SOURCE_CODE/Tourism_Web/Web/Views/Tours/Detail.cshtml
@model Web.Models.Tour

@{
    ViewBag.Title = "Detail";
    Layout = "~/Views/Shared/Layout.cshtml";
}

<div class="container-fluid bg-primary py-5 mb-5 hero-header">
    <div class="container py-5">
        <div class="row justify-content-center py-5">
            <div class="col-lg-10 pt-lg-5 mt-lg-5 text-center">
                <h1 class="display-3 text-white mb-3 animated slideInDown">Enjoy Your Vacation With Us</h1>
                <p class="fs-4 text-white mb-4 animated slideInDown">Tempor erat elitr rebum at clita diam amet diam et eos erat ipsum lorem sit</p>
                <form class="position-relative w-75 mx-auto animated slideInDown" action="/Tours/Index">
                    <input class="form-control border-0 rounded-pill w-100 py-3 ps-4 pe-5" type="search" id="search" name="search" placeholder="Eg: Hạ Long " value="@ViewBag.Search">
                    <button type="submit" class="btn btn-primary rounded-pill py-2 px-4 position-absolute top-0 end-0 me-2" style="margin-top: 7px;">Search</button>
                </form>
            </div>
        </div>
    </div>
</div>



<!-- Booking Start -->
<div class="container-xxl py-5 wow fadeInUp" data-wow-delay="0.1s">
    <div class="container-fluid">
        <div class="booking p-5">
            <div class="row g-5 align-items-center flex-row">
                <h2 style="align-content:center;" class="text-white">@Model.TenTour</h2>
                <div class="tour-details col-md-6 text-white">

                    <img src="data:image/jpeg;base64,@Convert.ToBase64String(Model.Hinh1.ToArray())" alt="Hình 1" style="width: 400px;">






                </div>
                <div class="tour-details col-md-6 text-white">

                    <p>@Model.MoTa</p>
                    <div class="flex-column">
                        <div>Ngày Đi: @Html.DisplayFor(model => model.NgayDi)</div>

                        <div>Ngày Về: @Html.DisplayNameFor(model => model.NgayVe)</div>
                        <div>Số ghế: @Html.DisplayNameFor(model => model.SoGhe)</div>
                        <div>
                            Điểm khởi hành: @Html.DisplayFor(model => model.DiemKhoiHanh)
                        </div>
                        <div>
                            Chỗ đã đặt: @Html.DisplayFor(model => model.SoNguoiDat)
                        </div>
                        <div>Giá: @Html.DisplayFor(model => model.Gia)/Người</div>
                        <div>
                            Giờ khởi hành: @Html.DisplayFor(model => model.GioKhoiHanh)
                        </div>


                    </div>

                    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.bundle.min.js"></script>



                </div>
                <a href="@Url.Action("XacNhanDatTour", "DatTour")" class="btn btn-sm btn-primary px-3" style="border-radius: 0 30px 30px 0;">Book Now</a>

            </div>

            <!-- Booking Start -->
        </div>
    </div>
</div>

SOURCE_CODE/Tourism_Web/Web/Views/Tours/Index.cshtml
@model List<Web.Models.Tour>
@using System.Data.Linq
@{
    ViewBag.Title = "Danh sách Tour";
    Layout = "~/Views/Shared/Layout.cshtml";
}
<div class="container-fluid bg-primary py-5 mb-5 hero-header">
    <div class="container py-5">
        <div class="row justify-content-center py-5">
            <div class="col-lg-10 pt-lg-5 mt-lg-5 text-center">
                <h1 class="display-3 text-white mb-3 animated slideInDown">Enjoy Your Vacation With Us</h1>
                <p class="fs-4 text-white mb-4 animated slideInDown">Tempor erat elitr rebum at clita diam amet diam et eos erat ipsum lorem sit</p>
                <form class="position-relative w-75 mx-auto animated slideInDown" action="/Tours/Index">
                    <input class="form-control border-0 rounded-pill w-100 py-3 ps-4 pe-5" type="search" id="search" name="search" placeholder="Eg: Hạ Long " value="@ViewBag.Search">
                    <button type="submit" class="btn btn-primary rounded-pill py-2 px-4 position-absolute top-0 end-0 me-2" style="margin-top: 7px;">Search</button>
                </form>
            </div>
        </div>
    </div>
</div>

<!-- Package Start -->
<div class="container-xxl py-5">
    <div class="container">
        <div class="text-center wow fadeInUp" data-wow-delay="0.1s">
            <h6 class="section-title bg-white text-center text-primary px-3">Packages</h6>
            <h1 class="mb-5">Awesome Packages</h1>
        </div>
        <div class="row g-4 justify-content-center">
            @foreach (var item in Model)
            {
                <div class="col-lg-4 col-md-6 wow fadeInUp" data-wow-delay="0.3s">
                    <div class="package-item">
                        <div class="overflow-hidden image-container">
                            @{
                                if (item.Hinh1.ToArray() != null)
                                {
                                    <img src="data:image/jpeg;base64,@Convert.ToBase64String(item.Hinh1.ToArray())" alt="Hình 1" style="width: 400px;">
                                }
                                else
                                {
                                    <img src="đường_dẫn_ảnh_mặc_định" alt="Ảnh Mặc Định" style="width: 400px;">
                                }
                            }

                            @*<img src="data:image/jpeg;base64,@Convert.ToBase64String(item.Hinh1.ToArray())" alt="Hình 1" style="width: 400px;">*@
                        </div>
                        <div class="d-flex border-bottom">
                            <small class="flex-fill text-center border-end py-2"><i class="fa fa-map-marker-alt text-primary me-2"></i>@item.TenTour</small>
                            <small class="flex-fill text-center border-end py-2"><i class="fa fa-calendar-alt text-primary me-2"></i>@ViewBag.SoNgayDi</small>
                            <small class="flex-fill text-center py-2"><i class="fa fa-user text-primary me-2"></i>@item.SoGhe</small>
                        </div>
                        <div class="text-center p-4">
                            <h3 class="mb-0">@item.Gia</h3>
                            <div class="mb-3">
                                <small class="fa fa-star text-primary"></small>
                                <small class="fa fa-star text-primary"></small>
                                <small class="fa fa-star text-primary"></small>
                                <small class="fa fa-star text-primary"></small>
                                <small class="fa fa-star text-primary"></small>
                            </div>
                            <p>@item.MoTa</p>
                            <div class="d-flex justify-content-center mb-2">
                                <a href="@Url.Content("/Tours/Detail/" + item.MaTour)" class="btn btn-sm btn-primary px-3 border-end" style="border-radius: 30px 0 0 30px;">Read More</a>
                                @*<a href="@Url.Content("/DatTour/XacNhanDatTour/" + item.MaTour)" class="btn btn-sm btn-primary px-3" style="border-radius: 0 30px 30px 0;">Book Now</a>*@
                                <a href="@Url.Action("XacNhanDatTour", "DatTour", new { id = item.MaTour })" class="btn btn-sm btn-primary px-3" style="border-radius: 0 30px 30px 0;">Book Now</a>

                            </div>
                        </div>
                    </div>
                </div>
            }


        </div>
    </div>
</div>
<!-- Package End -->